displayName=Group Ironman Tracker
author=Danj
description=Syncs Group Ironman drops, levels, quests, diaries, collection logs, boss sessions, and combat tasks across your group.
tags=GIM, Group Ironman, Tracker, Group, Ironman, drops, quests, diaries, collection log, combat tasks
plugins=com.dan.gimtracker.GIMTrackerPlugin
version=1.1.0
build=standard
